### ISSUE TITLE
Receiver discontinued?

### ISSUE THREAD

**Issue by ddavies1972** [AdrianVollmer/PowerHub#45]
In old versions of powerhub there seems to have been a receiver option that allowed to catch a reverse connection with the client.

This is a very useful feature. Can it be reimplemented?

Regards 

Darren

**Comment by AdrianVollmer** [comment]
Hi Darren,

I found that it wasn't working properly more often than it does, so I decided to remove it. In the spirit of PowerHub it makes more sense to load a 3rd party reverse shell. I often thought about publishing the reverse shell in a different repository, but the truth is that I simply don't need a reverse shell that often. Typically, getting the "loot" is enough, because then I can just psexec/wmiexec into the target. And I have trouble finding the motivation if I don't see the point in a feature. But that may change if enough people find the feature useful, so I'll leave this issue open.
